#ifndef SYSTEM_STATUS_H 
#define SYSTEM_STATUS_H

enum SystemStatus {
    SYSTEM_STARTING, 
    SYSTEM_STAND_BY, 
    SYSTEM_SAMPLING, 
    SYSTEM_SAMPLING_PARTIAL_ERROR, 
    SYSTEM_SAMPLE_FILE_UPLOAD, 
    SYSTEM_SAMPLE_FILE_UPLOAD_PARTIAL_ERROR, 
    SYSTEM_ERROR 
};

enum SamplerStatus {
    UNIT_STAND_BY,
    UNIT_SAMPLING,
    UNIT_ERROR,
    UNIT_SAMPLE_FILES_UPLOAD
};

#endif /* SYSTEM_STATUS_H */